#!/bin/bash
# SPDX-License-Identifier: MIT
set -e
# if no chart specified consider all
file=$1
overwrite=`yq r "$file" overwrite`
chart=`yq r "$file" chartName`
releaseName=`yq r "$file" releaseName`
releaseNamespace=`yq r "$file" releaseNamespace`
FILEVAL="$(mktemp)"
main=$(cat "$file" | yq r - values | yq p - values)
allresources=`cat`
# Is document stream!
count=0
retval=0
while [ $retval -eq 0 ]; do
  echo "$allresources" | yq r -d $count - &>/dev/null || retval=$?
  if [ $retval -eq 0 ]; then
    kind=`echo "$allresources" | yq r -d $count - kind`
    name=`echo "$allresources" | yq r -d $count - chartName`
    if [ $kind == "HelmChart" ]; then
      # Helm way
      # If the chart Name is specified apply the whole enchilada
      if [ -z $chart ] || [ "$chart" == "null" ] || [ "$name" == "$chart" ]; then
        echo "$main" > "$FILEVAL"
        if [ "$overwrite" != "false" ]; then
          allresources=$(echo "$allresources" | yq m -d $count -x - "$FILEVAL")
        else
          allresources=$(echo "$allresources" | yq m -d $count - "$FILEVAL")
        fi
      fi
      # Is the chart listed as a first level sub-chart? Yeah? then apply
      values=$(echo "$main" | yq r - values."$name")
      if [ ! -z "$values" ] && [ "$values" != "null" ]; then
        echo "$values" | yq p - values > "$FILEVAL"
        if [ "$overwrite" != "false" ]; then
          allresources=$(echo "$allresources" | yq m -d $count -x - "$FILEVAL")
        else
          allresources=$(echo "$allresources" | yq m -d $count - "$FILEVAL")
        fi
      fi
      if [ ! -z $releaseNamespace ] && [ "$releaseNamespace" != "null" ]; then
        allresources=$(echo "$allresources" | yq w -d $count - releaseNamespace "$releaseNamespace")
      fi
      if [ ! -z $releaseName ] && [ "$releaseName" != "null" ]; then
        allresources=$(echo "$allresources" | yq w -d $count - releaseName "$releaseName")
      fi
    fi
  fi
  count=$(expr $count + 1)
done
echo "$allresources"
