argocd app sync audit
argocd app sync chronos
argocd app sync chronos-worker
argocd app sync collections
argocd app sync data-connector-odbc
argocd app sync data-connector-qwc
argocd app sync data-connector-rest
argocd app sync data-prep
argocd app sync data-rest-source
argocd app sync dcaas
argocd app sync dcaas-web
argocd app sync edge-auth
argocd app sync elastic-infra
argocd app sync encryption
argocd app sync engine
argocd app sync feature-flags
argocd app sync groups
argocd app sync hub
argocd app sync identity-providers
argocd app sync keys
argocd app sync licenses
argocd app sync locale
argocd app sync management-console
argocd app sync messaging
argocd app sync mongodb
argocd app sync odag
argocd app sync policy-decisions
argocd app sync qix-data-connection
argocd app sync qix-datafiles
argocd app sync qix-sessions
argocd app sync qliksense
argocd app sync redis
argocd app sync reporting
argocd app sync resource-library
argocd app sync sense-client
argocd app sync spaces
argocd app sync temporary-contents
argocd app sync tenants
argocd app sync users
argocd app sync resources